#!/bin/bash
# NeuralBlitz Encrypted Backup Script
# Usage: ./backup.sh [encrypt]

set -e

BACKUP_DIR="/home/runner/workspace/backups"
DATE=$(date +%Y%m%d_%H%M%S)
BACKUP_NAME="neuralblitz_backup_${DATE}"

# Create backup directory
mkdir -p "$BACKUP_DIR"

# Directories to backup (CRITICAL ASSETS ONLY)
CRITICAL_DIRS=(
    "NBX-LRS"
    "NB-Ecosystem"
    "Emergent-Prompt-Architecture"
    "opencode-lrs-agents-nbx"
    "Advanced-Research"
    "quantum_sim"
    "lrs-agents"
    "ComputationalAxioms"
)

echo "🧠 Creating NeuralBlitz backup..."
echo "📅 Date: $DATE"

# Create temporary backup
TEMP_BACKUP="/tmp/${BACKUP_NAME}.tar.gz"
tar -czf "$TEMP_BACKUP" \
    --exclude='.git' \
    --exclude='node_modules' \
    --exclude='__pycache__' \
    --exclude='*.pyc' \
    --exclude='.env' \
    "${CRITICAL_DIRS[@]}"

# Get size
SIZE=$(du -h "$TEMP_BACKUP" | cut -f1)
echo "📦 Backup created: ${BACKUP_NAME}.tar.gz ($SIZE)"

# Encrypt if requested
if [ "$1" == "encrypt" ]; then
    echo "🔒 Encrypting backup (using openssl)..."
    ENCRYPTED_BACKUP="${BACKUP_DIR}/${BACKUP_NAME}.tar.gz.enc"
    openssl enc -aes-256-cbc -salt -pbkdf2 -in "$TEMP_BACKUP" -out "$ENCRYPTED_BACKUP" -pass pass:neuralblitz_backup_key
    rm "$TEMP_BACKUP"
    echo "✅ Encrypted backup: ${BACKUP_NAME}.tar.gz.enc"
    echo "⚠️  IMPORTANT: Save this decryption command:"
    echo "   openssl enc -aes-256-cbc -d -pbkdf2 -in ${BACKUP_NAME}.tar.gz.enc -out restored.tar.gz -pass pass:neuralblitz_backup_key"
else
    mv "$TEMP_BACKUP" "${BACKUP_DIR}/${BACKUP_NAME}.tar.gz"
    echo "✅ Backup saved: ${BACKUP_DIR}/${BACKUP_NAME}.tar.gz"
fi

# Create manifest
MANIFEST="${BACKUP_DIR}/${BACKUP_NAME}_manifest.txt"
echo "NeuralBlitz Backup Manifest" > "$MANIFEST"
echo "===========================" >> "$MANIFEST"
echo "Date: $DATE" >> "$MANIFEST"
echo "Directories:" >> "$MANIFEST"
for dir in "${CRITICAL_DIRS[@]}"; do
    SIZE=$(du -sh "$dir" 2>/dev/null | cut -f1 || echo "N/A")
    echo "  - $dir ($SIZE)" >> "$MANIFEST"
done
echo "" >> "$MANIFEST"
echo "Generated by backup script" >> "$MANIFEST"

echo "📝 Manifest created: ${BACKUP_NAME}_manifest.txt"

# Cleanup old backups (keep last 7)
echo "🧹 Cleaning up old backups..."
find "$BACKUP_DIR" -name "neuralblitz_backup_*.tar.gz" -mtime +7 -delete
find "$BACKUP_DIR" -name "neuralblitz_backup_*.tar.gz.enc" -mtime +7 -delete
find "$BACKUP_DIR" -name "neuralblitz_backup_*.txt" -mtime +7 -delete

echo "✅ Backup complete!"
