# UAID: NBX-ALG-00014
# GoldenDAG: c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4
#
# NeuralBlitz UEF/SIMI v11.1
# Core Algorithm: Bloom Event Timeline Renderer
# Part of the Self-Reflection_Logs Subsystem
#
# Core Principle: Radical Transparency (ε₂) - visualizing the system's own evolution.

import json
from pathlib import Path
import datetime as dt
from typing import List, Dict
# Matplotlib is the designated python_user_visible tool for plotting.
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

class BloomTimelineRenderer:
    """
    Parses a bloom alert log file and generates a visual timeline of
    Bloom and Hyperbloom events, plotting entropy levels over time.
    """

    def __init__(self, log_jsonl_path: str):
        """
        Initializes the renderer with the path to the log file.

        Args:
            log_jsonl_path (str): Path to the .jsonl file generated by the
                                  BloomEventDetector.
        """
        self.log_path = Path(log_jsonl_path)
        if not self.log_path.exists():
            raise FileNotFoundError(f"ERR-FS-009: Bloom log file not found at '{self.log_path}'")
        
        self.events = self._load_events()

    def _load_events(self) -> List[Dict]:
        """Loads and parses all valid event entries from the log file."""
        loaded_events = []
        with self.log_path.open('r') as f:
            for line in f:
                try:
                    data = json.loads(line)
                    # We are only interested in the actual alert events, not the summary header
                    if data.get("event_type") == "BLOOM_DETECTED":
                        # Convert timestamp string to a datetime object for plotting
                        data['timestamp_dt'] = dt.datetime.fromisoformat(data['timestamp'].replace('Z', '+00:00'))
                        loaded_events.append(data)
                except (json.JSONDecodeError, KeyError, ValueError) as e:
                    print(f"Warning: Skipping malformed log line in '{self.log_path.name}'. Reason: {e}")
        
        # Sort events chronologically
        return sorted(loaded_events, key=lambda x: x['timestamp_dt'])

    def render_plot(self, output_png_path: str):
        """
        Generates and saves a matplotlib plot of the bloom event timeline.

        Args:
            output_png_path (str): The path to save the generated .png file.
        """
        if not self.events:
            print("Info: No bloom events found in log file. Cannot generate plot.")
            return

        dates = [event['timestamp_dt'] for event in self.events]
        entropy_levels = [event['entropy'] for event in self.events]
        
        # Take the baseline from the first event's metadata
        mean_entropy = self.events[0].get('mean_entropy')
        alert_threshold = self.events[0].get('threshold')

        # --- Plotting with Matplotlib ---
        fig, ax = plt.subplots(figsize=(15, 7))

        # Plot the entropy levels as a stem plot
        markerline, stemlines, baseline = ax.stem(
            dates,
            entropy_levels,
            linefmt='grey',
            markerfmt='o',
            bottom=mean_entropy if mean_entropy is not None else 0
        )
        plt.setp(stemlines, 'linewidth', 1, 'color', 'royalblue')
        plt.setp(markerline, 'markersize', 6, 'color', 'royalblue')
        plt.setp(baseline, 'color', 'grey', 'linewidth', 1, 'linestyle', '--')


        # Plot the baseline and threshold lines
        if mean_entropy is not None:
            ax.axhline(y=mean_entropy, color='grey', linestyle='--', linewidth=1, label=f'Mean Entropy Baseline ({mean_entropy:.2f})')
        if alert_threshold is not None:
            ax.axhline(y=alert_threshold, color='red', linestyle='-', linewidth=1.5, label=f'Bloom Alert Threshold ({alert_threshold:.2f})')
        
        # Formatting the plot for readability
        ax.set_title('NeuralBlitz - DRS Latent Space Bloom Events Timeline', fontsize=16)
        ax.set_ylabel('Shannon Entropy (Effective Dimensionality)', fontsize=12)
        ax.set_xlabel('Event Timestamp (UTC)', fontsize=12)
        ax.legend()
        ax.grid(True, which='both', linestyle=':', linewidth=0.5)

        # Improve date formatting on the x-axis
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M'))
        plt.gcf().autofmt_xdate() # Auto-rotate date labels

        plt.tight_layout()
        
        # Save the plot to the specified file
        plt.savefig(output_png_path, dpi=150)
        print(f"Bloom timeline visualization saved to: {output_png_path}")

if __name__ == '__main__':
    # --- Example NBCL Invocation Simulation ---
    # NBCL Command: /invoke visualizer --render_bloom_timeline --log="/Self-Reflection_Logs/bloom_alerts.jsonl"

    print("--- Initiating NeuralBlitz Bloom Timeline Renderer ---")

    # Create a dummy log file for the simulation
    log_file = Path("bloom_alerts_sim.jsonl")
    
    # We will need some fake event data
    now = dt.datetime.utcnow()
    dummy_log_content = [
        {"event_type": "BLOOM_DETECTED", "timestamp": (now - dt.timedelta(hours=5)).isoformat() + "Z", "entropy": 7.8, "mean_entropy": 7.5, "threshold": 8.5},
        {"event_type": "BLOOM_DETECTED", "timestamp": (now - dt.timedelta(hours=4)).isoformat() + "Z", "entropy": 7.6, "mean_entropy": 7.5, "threshold": 8.5},
        # This one is a significant bloom
        {"event_type": "BLOOM_DETECTED", "timestamp": (now - dt.timedelta(hours=3)).isoformat() + "Z", "entropy": 9.1, "mean_entropy": 7.5, "threshold": 8.5},
        {"event_type": "BLOOM_DETECTED", "timestamp": (now - dt.timedelta(hours=2)).isoformat() + "Z", "entropy": 8.2, "mean_entropy": 7.5, "threshold": 8.5},
        {"event_type": "BLOOM_DETECTED", "timestamp": (now - dt.timedelta(hours=1)).isoformat() + "Z", "entropy": 8.6, "mean_entropy": 7.5, "threshold": 8.5},
    ]

    with log_file.open('w') as f:
        # A header summary might also be in the real log, which the loader should ignore
        f.write(json.dumps({"summary": "This is not an event"}) + '\n')
        for event in dummy_log_content:
            f.write(json.dumps(event) + '\n')

    print(f"Created dummy log file: {log_file}")
    
    try:
        renderer = BloomTimelineRenderer(str(log_file))
        output_image = "bloom_timeline.png"
        renderer.render_plot(output_image)

        print(f"\nSuccessfully generated plot '{output_image}'.")
        print("The plot shows entropy levels over time, with the 9.1 event clearly crossing the alert threshold.")
    except Exception as e:
        print(f"\nAn error occurred during the simulation: {e}")
    finally:
        # Clean up the dummy file
        log_file.unlink(missing_ok=True)
        # In a real run, you'd keep the output image.
        Path("bloom_timeline.png").unlink(missing_ok=True)